### PR TITLE
Move loop creation out of onReady, as the database is not established that early.

### PR DESCRIPTION
**Pull request by AkbarTheGreat**
The old code didn't have to worry about this, since it was just reading from a file system, but now that we're reading from a database, we need to ensure the db connection is live before we start doing operations that depend on it.

### CODE REVIEW

**Comment by AkbarTheGreat** [comment]
My bad, I didn't mean to push this all the way back up!

You're welcome to take anything I'm working on, if it's useful to you, but I didn't mean to burden you with it.  My bad!

**Comment by azjps** [comment]
@AkbarTheGreat Thanks and no problem, glad to hear you (and I think a couple other teams) were able to make use of this. I might do my customary last minute sprint and pull in some of these changes.

**Comment by azjps** [comment]
@AkbarTheGreat I did end up using your fork and added some additional features / maintenance on top: https://github.com/azjps/ladder_dogs_discord_bot/tree/splat2024 thanks again! Have credited in `README` :)

**Comment by AkbarTheGreat** [comment]
@azjps -- Oh, rad!  I've still got a laundry list of things to do (like re-enabling notes), but I'm glad you found some use there -- also, I'm happy to see you cleaning up some of my mess with the gino implementation (Python is something like my fourth best language, and I definitely hadn't dealt with Sqlalchemy or Gino before now, so it's a little bit of me muddling through stuff while I figure it out).

Anyway, I'll get my fork rebased to your splat2024 branch so I can take advantage of your improvements, and I'll be sure to send you periodic PRs to that branch as I get stuff hammered out.

Thanks for giving me such good bones to build on top of, this bot has been really great for our team so far  :)

**Comment by azjps** [comment]
@AkbarTheGreat sweet, FYI I re-added (a fairly primitive) notes support with this db table: https://github.com/azjps/ladder_dogs_discord_bot/blob/7478c3f898230630c83a631caa85a4eb07c1b2c4/bot/database/models/puzzle_data.py#L84
image

**Pull request closed without merging**
